# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'WeChatMoments' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for WeChatMoments
  pod 'Alamofire', '~> 5.2'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod "PromiseKit", "~> 6.8"
  pod 'SnapKit', '~> 5.0.1'
  pod 'Kingfisher', '~> 6.3.0'

  target 'WeChatMomentsTests' do
    inherit! :search_paths
    pod 'OHHTTPStubs/Swift'
  end

end
